### ISSUE TITLE
Adjust lint rules to accommodate autogenerated Python hoprd api client

### ISSUE THREAD

**Issue by trincema** [hoprnet/hoprd-test#1]
### Description
In order to run the hoprd automated tests, some infrastructure setup is needed, so we can start with the following basic points:

1. Python dependency and swagger_client from https://github.com/hoprnet/hoprd-api-python repo.
2. Binaries to setup local blockchain
2.1. Foundry binaries: `anvil`, `cast`, `forge`
2.2. `hopli` as an executable binary (`hoprnet/packages/hopli`)

### Definition of DONE

- [x] Python setup with [swagger_client](https://github.com/hoprnet/hoprd-api-python) installed
- [x] Foundry setup so that I can call from the terminal `anvil`, `cast`, `forge` as commands
- [x] Hopli setup so that i can call from the terminal `hopli` as command
- [x] Install `nodejs` so that we can run node command to setup nodes
- [ ] Install `hoprd` with all dependencies (perhaps install `hoprnet` altogether)

**Comment by sitilge** [comment]
IMO, this can be closed as per this: https://github.com/hoprnet/hopraf/pull/3

**Comment by trincema** [comment]
I also need nodejs installed so that I can setup nodes, forgot about that.

**Comment by sitilge** [comment]
@trincema which node version do you need?

**Comment by sitilge** [comment]
Node 16 has been installed as per this: https://github.com/hoprnet/hopraf/actions/runs/5462808136/jobs/9942667597 . Feel free to update the version to what you need.
